using System.Text.Json.Serialization;

namespace SauceNao.NET.Client.PixivModel; 

public record Illustration(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("illustType")] int IllustType,
    [property: JsonPropertyName("xRestrict")] int XRestrict,
    [property: JsonPropertyName("restrict")] int Restrict,
    [property: JsonPropertyName("sl")] int Sl,
    [property: JsonPropertyName("url")] string? Url,
    [property: JsonPropertyName("description")] string Description,
    // [property: JsonPropertyName("tags")] IReadOnlyList<string> Tags,
    [property: JsonPropertyName("userId")] string UserId,
    [property: JsonPropertyName("userName")] string UserName,
    [property: JsonPropertyName("width")] int Width,
    [property: JsonPropertyName("height")] int Height,
    [property: JsonPropertyName("pageCount")] int PageCount,
    // [property: JsonPropertyName("isBookmarkable")] bool IsBookmarkable,
    // [property: JsonPropertyName("bookmarkData")] object BookmarkData,
    [property: JsonPropertyName("alt")] string Alt,
    // [property: JsonPropertyName("titleCaptionTranslation")] TitleCaptionTranslation TitleCaptionTranslation,
    [property: JsonPropertyName("createDate")] DateTime CreateDate,
    [property: JsonPropertyName("updateDate")] DateTime? UpdateDate,
    // [property: JsonPropertyName("isUnlisted")] bool IsUnlisted,
    // [property: JsonPropertyName("isMasked")] bool? IsMasked,
    // [property: JsonPropertyName("aiType")] int AiType,
    // [property: JsonPropertyName("profileImageUrl")] string? ProfileImageUrl,
    [property: JsonPropertyName("illustId")] string? IllustId,
    [property: JsonPropertyName("illustTitle")] string? IllustTitle,
        // [property: JsonPropertyName("illustComment")] string IllustComment,
    [property: JsonPropertyName("uploadDate")] DateTime? UploadDate,
    [property: JsonPropertyName("urls")] Urls? Urls,
    [property: JsonPropertyName("userAccount")] string? UserAccount,
    [property: JsonPropertyName("userIllusts")] Dictionary<string, Illustration>? UserIllusts
    // [property: JsonPropertyName("likeData")] bool LikeData,
    // [property: JsonPropertyName("bookmarkCount")] int BookmarkCount,
    // [property: JsonPropertyName("likeCount")] int LikeCount,
    // [property: JsonPropertyName("commentCount")] int CommentCount,
    // [property: JsonPropertyName("responseCount")] int ResponseCount,
    // [property: JsonPropertyName("viewCount")] int ViewCount,
    // [property: JsonPropertyName("bookStyle")] int BookStyle,
    // [property: JsonPropertyName("isHowto")] bool IsHowto,
    // [property: JsonPropertyName("isOriginal")] bool IsOriginal,
    // [property: JsonPropertyName("imageResponseOutData")] IReadOnlyList<object> ImageResponseOutData,
    // [property: JsonPropertyName("imageResponseData")] IReadOnlyList<object> ImageResponseData,
    // [property: JsonPropertyName("imageResponseCount")] int ImageResponseCount,
    // [property: JsonPropertyName("pollData")] object PollData,
    // [property: JsonPropertyName("seriesNavData")] object SeriesNavData,
    // [property: JsonPropertyName("descriptionBoothId")] object DescriptionBoothId,
    // [property: JsonPropertyName("descriptionYoutubeId")] object DescriptionYoutubeId,
    // [property: JsonPropertyName("comicPromotion")] object ComicPromotion,
    // [property: JsonPropertyName("fanboxPromotion")] object FanboxPromotion,
    // [property: JsonPropertyName("contestBanners")] IReadOnlyList<object> ContestBanners,
    // [property: JsonPropertyName("contestData")] object ContestData,
    // [property: JsonPropertyName("zoneConfig")] ZoneConfig ZoneConfig,
    // [property: JsonPropertyName("extraData")] ExtraData ExtraData,
    // [property: JsonPropertyName("titleCaptionTranslation")] TitleCaptionTranslation TitleCaptionTranslation,
    // [property: JsonPropertyName("request")] object Request,
    // [property: JsonPropertyName("commentOff")] int CommentOff,
    // [property: JsonPropertyName("noLoginData")] NoLoginData NoLoginData
);